//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationLocamer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mobilhome
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mobilhome()
        {
            this.Sejour = new HashSet<Sejour>();
        }
    
        public int id_mobil { get; set; }
        public int id_tarif { get; set; }
        public string libelle_mobil { get; set; }
        public int emplacement_mobil { get; set; }
        public int capacite_mobil { get; set; }
        public bool terasse_mobil { get; set; }
    
        public virtual Type_tarif Type_tarif { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sejour> Sejour { get; set; }
    }
}
